#!/bin/zsh

if ! command -v doas >/dev/null 2>&1 && command -v sudo >/dev/null 2>&1; then
    doas() { sudo "$@"; }
fi
if ! command -v sudo >/dev/null 2>&1 && command -v doas >/dev/null 2>&1; then
    sudo() { doas "$@"; }
fi

alias vim="nvim" vimdiff="nvim -d"

sc() {
  s=("${HOME}/.local/bin/"*.sh)
  c="$(print -lnr ${s:t:r} | fzf)"
  [[ "${c}" ]] && nvim ${${(M)s:#*/${c}.sh}[1]}
}
po() {
  s=("/etc/portage/"**/*(D.))
  c="$(print -lnr ${s#/etc/portage/} | fzf)"
  [[ "${c}" ]] && doas nvim "/etc/portage/${c}"
}

alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	bc="bc -ql" \
	mkd="mkdir -pv" \
	cat="bat -P" \
	yt="yt-dlp" \
	ffmpeg="ffmpeg -hide_banner" \

alias \
	ll="eza -lh --group-directories-first --color=always --color-scale=all --color-scale-mode=fixed --icons=always --no-quotes --smart-group -s size --total-size --no-user --no-permissions" \
	ls="eza --group-directories-first --color=always --icons --no-quotes -s name" \
	lsf="eza -f --group-directories-first --color=always --icons --no-quotes -s name" \
	lsd="eza -D --group-directories-first --color=always --icons --no-quotes -s name" \
	lst="eza -lh --group-directories-first --color=always --icons --no-quotes --smart-group -s time --total-size --no-user --no-permissions" \
	chrome="nvim .librewolf/*/chrome/userChrome.css" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \

alias \
	ka="killall" \
	e="$EDITOR" \
	v="$EDITOR" \
	emg="doas emerge --ask --update --newuse @world" \

sms() {
    if grep -q "Arch Linux" /etc/os-release 2>/dev/null; then
        maintain_arch.sh "$@"
    else
        doas maintain_gentoo.sh "$@"
    fi
}
