font=BlexMono Nerd Font Mono:size=12:weight=medium
pad=0x0

[colors-dark]
background=000000
foreground=e8e8e8

## Normal colors
regular0=000000
regular1=da3030
regular2=30F7BE
regular3=F8FD00
regular4=99d8fe
regular5=d484fb
regular6=3bf0f4
regular7=e8e8e8

## Bright colors
bright0=1c272a
bright1=f95556
bright2=94fed6
bright3=EEFF50
bright4=b3e2fe
bright5=e9c4fd
bright6=80f9fc
bright7=ffffff

## Selection
selection-background=463465
selection-foreground=e8e8e8

## Cursor
cursor=000000 3bf0f4
