hl.workspace_rule({ workspace = "1", default = true, default_name = "" })
hl.workspace_rule({ workspace = "2", default_name = "" })
hl.workspace_rule({ workspace = "3", default_name = "" })
hl.workspace_rule({ workspace = "4", default_name = "" })
hl.workspace_rule({ workspace = "5", default_name = "" })
hl.workspace_rule({ workspace = "6", default_name = "" })
hl.workspace_rule({ workspace = "7", default_name = "" })
hl.workspace_rule({ workspace = "8", default_name = "" })
hl.workspace_rule({ workspace = "9", default_name = "" })
hl.workspace_rule({ workspace = "10", default_name = "" })
